[dependencies]
base = "0.12.1"
motoko-base = "https://github.com/dfinity/motoko-base#master@e1b5bba80a9ef1faacfcffa3e8f64ab84d60c570"
"array.mo" = "https://github.com/aviate-labs/array.mo#master@8e4282825d3b401407954917cd94d1548ee21256"
"encoding.mo" = "https://github.com/aviate-labs/encoding.mo#master@2711d18727e954b11afc0d37945608512b5fbce2"
"io.mo" = "https://github.com/aviate-labs/io.mo#master@6492419a1592b3346085c32cadb98c5a9ff71075"
"uuid.mo" = "https://github.com/aviate-labs/uuid.mo#master@b88101f0516847727ff45ea54688803c698935e5"
motoko-sha = "https://github.com/tgalal/motoko-sha#master@9e2468f51ef060ae04fde8d573183191bda30189"
motoko-bitcoin = "https://github.com/tgalal/motoko-bitcoin#master@10cf7f2efbba9bb4d077013db1b990143f193844"
cap = "https://github.com/stephenandrews/cap-motoko-library#master@f3332361111e20788c9ecabba714332b31fbd5fb"
uuid = "1.0.0"
crypto = "https://github.com/Bochslertech/crypto"
ext = "https://github.com/Bochslertech/ext#v0.1"
hash = "https://github.com/aviate-labs/hash.mo#v0.1.0"
principal = "https://github.com/aviate-labs/principal.mo#v0.2.4"
parser-combinators = "https://github.com/aviate-labs/parser-combinators.mo#v0.1.0"
json = "https://github.com/aviate-labs/json.mo#v0.1.2"
canistergeek = "https://github.com/usergeek/canistergeek-ic-motoko#v0.0.4"
cap-motoko-library = "https://github.com/stephenandrews/cap-motoko-library#master@f3332361111e20788c9ecabba714332b31fbd5fb"
